[package]
name = "flux-capacitor"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3"
crossbeam = "0.8.4"
tokio = { version = "1.46.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.9"
rand = "0.9.1"
ringbuffer = "0.15"
